### ISSUE TITLE
Nested clasp projects are not supported.

### ISSUE THREAD

**Issue by antony** [labnol/apps-script-starter#19]
Trying to follow the instructions from the readme, but fails at the first step, I get "nested clasp projects are not supported"

```
 ant@xeno  ~/Projects/apps-script-starter  npx clasp create --title "Hot Garbage" --rootDir ./dist
> Create which script?
standalone

Nested clasp projects are not supported.
```

**Comment by kimbim** [comment]
Same here!

**Comment by labnol** [comment]
Could you please post more details here. I tried it again and seem to work.

```
npx clasp create --title "Hot Garbage" --rootDir ./dist
? Create which script? standalone
Created new standalone script: https://script.google.com/d/1234/edit
Warning: files in subfolder are not accounted for unless you set a '.claspignore' file.
Cloned 1 file.
└─ ./dist/appsscript.json
```

**Comment by coisnepe** [comment]
Also getting the same error...

**Comment by pavittarx** [comment]
I am experiencing the same. Here is the output from my terminal 
![image](https://user-images.githubusercontent.com/29155477/93447469-10727f00-f8f0-11ea-9140-f577f2940f34.png)

**Comment by pavittarx** [comment]
I was able to resolve the issue, I found an `.clasp.json` file located one directory above the project directory. `./../` . Removing the filr `./../.clasp.json` resolves the issue. 

`./` is the directory you are executing the command `npx clasp create`

**Comment by Akhil-Raj** [comment]
> I was able to resolve the issue, I found an `.clasp.json` file located one directory above the project directory. `./../` . Removing the filr `./../.clasp.json` resolves the issue.
> 
> `./` is the directory you are executing the command `npx clasp create`

Worked for me
