### ISSUE TITLE
clasp Push failed. Errors: Project contents must include a manifest file named appsscript.

### ISSUE THREAD

**Issue by oshliaer** [labnol/apps-script-starter#2]
I'm confused.

`npm run deploy` is finished with the error:

```bash
...
Push failed. Errors:
Project contents must include a manifest file named appsscript.
Files to push were:
└─ dist/code.js
└─ dist/index.html
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apps-script-starter@1.0.4 deploy: `npm run build && ls -ah ./dist && clasp push`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apps-script-starter@1.0.4 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-08-02T09_56_54_294Z-debug.log
```

If I run `clasp push` directly it works fine.

I've checked `CopyWebpackPlugin` it works fine too.

Also I tracked files in the directory. I'm on Linux

*package.json*
```json
 "scripts": {
    "deploy_test": "npm run build && ls -ah ./dist && clasp push"
  },
```
*output*
```bash
...
.  ..  appsscript.json  code.js  index.html
Push failed. Errors:
Project contents must include a manifest file named appsscript.
Files to push were:
└─ dist/code.js
└─ dist/index.html
```

As can you see the file is there.

Any ideas how to fix this?

**Comment by oshliaer** [comment]
At now I think the problem in my console because the next script works

*package.json*
```json
"deploy": "npm run build && ls -ah ./dist && exit 0"
```

```bash
$ npm run deploy && clasp push
```

**Comment by oshliaer** [comment]
Ok. After some tests the next command doesn't work on my system
_package.json_
```json
...
"push": "clasp push",
...
```
_terminal_
```bash
npm run push

> apps-script-starter@1.0.4 push /home/user/tmp/apps-script-starter
> clasp push

Push failed. Errors:
Project contents must include a manifest file named appsscript.
Files to push were:
└─ dist/code.js
└─ dist/index.html
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apps-script-starter@1.0.4 push: `clasp push`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apps-script-starter@1.0.4 push script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-08-02T12_16_15_335Z-debug.log
```

**Comment by labnol** [comment]
This is an issue with the most recent version of clasp. Switch to clasp 1.4.1 in the package.json and it would work. For some reason, the newer versions of clasp are skipping appscript.json file in the distribution folder.

**Comment by oshliaer** [comment]
@labnol , it's true. Thanks!

**Comment by labnol** [comment]
The issue is specific to Google Clasp v1.5.2 though it works with the 1.4 release.

`➜ ls dist
appsscript.json 
code.js         
oauth2.js

➜ npx clasp status
Not ignored files:
└─ dist/code.js
└─ dist/oauth2.js

Ignored files:
└─ dist/appsscript.json

➜ npx clasp push
Push failed. Errors:
Project contents must include a manifest file named appsscript.
Files to push were:
└─ dist/code.js
└─ dist/oauth2.js
`

**Comment by labnol** [comment]
@google/clasp 1.5.3 fixes this issue.
