### ISSUE TITLE
Pushing with clasp results in badRequest

### ISSUE THREAD

**Issue by vrendy** [labnol/apps-script-starter#20]
Following the video on YouTube "Google Apps Script", after running 'npm run build', 'npx clasp push', results in
`message: 'Syntax error: Missing : after property ID. line: 11 file: webpack.config'`
line 11 in webpack.config is:
`const { CleanWebpackPlugin } = require('clean-webpack-plugin');`
At the end of the console it says:
"Pushed x files."
But when I open the Apps Script online, the files have not been updated.

**Comment by toddwilson7** [comment]
Try npm run deploy

**Comment by vrendy** [comment]
That did it, thanks!

**Comment by labnol** [comment]
This likely happens when the "rootDir" property is not set in the .clasp.json file. When rootDir is missing, clasp will try to push all files from the root folder into the Google Apps Script project including webpack.config.js and that likely leads to this error.
