### ISSUE TITLE
Error: Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by canuradha** [labnol/apps-script-starter#22]
After the latest commit to integrate V8 Runtime Support "npm run build" gives the above error even for the initial build as well. This can be resolved by re-adding the @bable/core module (which was removed in the V8 runtime support commit) but I don't think it will accomplish the V8 integration.

**Comment by basil2style** [comment]
@canuradha It's giving me the same error even if I re add the babel module.

**Comment by basil2style** [comment]
It's working for me now when I updated the package.json
_"babel-loader": "^8.0.6"_

**Comment by labnol** [comment]
[Resolved](https://github.com/labnol/apps-script-starter/commit/e55195ad675ec40e1cc9d51dcc6d86161ab32d3d).
