### ISSUE TITLE
"appsscript.json" has errors: Invalid manifest: Expected one of [V8, STABLE, DEPRECATED_ES5] for "runtimeVersion", but was "v8"

### ISSUE THREAD

**Issue by EmericHochart** [labnol/apps-script-starter#23]
https://github.com/labnol/apps-script-starter/blob/f96be9978f1ff9da0723da9e9e06bc042e40ab75/appsscript.json#L3

this error appears when launching the command "npm run deploy"

Issue : Expected V8 instead v8

**Comment by basil2style** [comment]
@EmericHochart, 

1. Replace "v8" with "V8" 
2. npm run build 
3. npx clasp push

**Comment by labnol** [comment]
[Resolved](https://github.com/labnol/apps-script-starter/commit/e55195ad675ec40e1cc9d51dcc6d86161ab32d3d).
