### ISSUE TITLE
npm run build - failed

### ISSUE THREAD

**Issue by ftharyanto** [labnol/apps-script-starter#26]
Hello, I tried to run `npm run build` but failed
![image](https://user-images.githubusercontent.com/17604130/77791883-bf08d600-70aa-11ea-8aad-718641d711be.png)

**this is the complete log:**
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle apps-script-starter@4.9.0~prebuild: apps-script-starter@4.9.0
6 info lifecycle apps-script-starter@4.9.0~build: apps-script-starter@4.9.0
7 verbose lifecycle apps-script-starter@4.9.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle apps-script-starter@4.9.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/ayato/Data/Projects/github/echo-bot/echo-bot/node_modules/.bin:/home/ayato/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle apps-script-starter@4.9.0~build: CWD: /media/ayato/Data/Projects/github/echo-bot/echo-bot
10 silly lifecycle apps-script-starter@4.9.0~build: Args: [ '-c', 'webpack' ]
11 silly lifecycle apps-script-starter@4.9.0~build: Returned: code: 2  signal: null
12 info lifecycle apps-script-starter@4.9.0~build: Failed to exec build script
13 verbose stack Error: apps-script-starter@4.9.0 build: `webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid apps-script-starter@4.9.0
15 verbose cwd /media/ayato/Data/Projects/github/echo-bot/echo-bot
16 verbose Linux 5.3.0-26-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v13.8.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 2
22 error apps-script-starter@4.9.0 build: `webpack`
22 error Exit status 2
23 error Failed at the apps-script-starter@4.9.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]`

**Comment by Kirajav** [comment]
any progress with this problem?

**Comment by ftharyanto** [comment]
> any progress with this problem?

nope :(

**Comment by labnol** [comment]
Please see https://github.com/labnol/apps-script-starter/issues/27
