### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by Kirajav** [labnol/apps-script-starter#27]
Hello!
Excuse me Sir, but i'm a newbie with this git project and i'm trying to learn following your youtube video example and i got this error when i type: `npm run build`

`jjavi@KIRAHP MINGW64 /d/jjavi/Documents/git clones/apps-script-starter
$ npm run build

> apps-script-starter@4.9.0 build D:\jjavi\Documents\git clones\apps-script-starter
> webpack

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization.minimize should be a boolean.
   -> Enable minimizing the output. Uses optimization.minimizer.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apps-script-starter@4.9.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apps-script-starter@4.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jjavi\AppData\Roaming\npm-cache\_logs\2020-03-28T09_22_27_027Z-debug.log
`
the complete log:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle apps-script-starter@4.9.0~prebuild: apps-script-starter@4.9.0
6 info lifecycle apps-script-starter@4.9.0~build: apps-script-starter@4.9.0
7 verbose lifecycle apps-script-starter@4.9.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle apps-script-starter@4.9.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\jjavi\Documents\git clones\apps-script-starter\node_modules\.bin;C:\Users\jjavi\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\jjavi\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\jjavi\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\jjavi\AppData\Local\Programs\Python\Python37-32;C:\Users\jjavi\AppData\Local\Microsoft\WindowsApps;C:\Users\jjavi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Mingw-w64\mingw64\bin;C:\adb;C:\Program Files (x86)\Universal Extractor;C:\Program Files (x86)\Universal Extractor\bin;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Users\jjavi\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\jjavi\AppData\Local\Programs\Python\Python37-32;C:\Users\jjavi\AppData\Local\Microsoft\WindowsApps;C:\Users\jjavi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Mingw-w64\mingw64\bin;C:\Users\jjavi\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle apps-script-starter@4.9.0~build: CWD: D:\jjavi\Documents\git clones\apps-script-starter
10 silly lifecycle apps-script-starter@4.9.0~build: Args: [ '/d /s /c', 'webpack' ]
11 silly lifecycle apps-script-starter@4.9.0~build: Returned: code: 1  signal: null
12 info lifecycle apps-script-starter@4.9.0~build: Failed to exec build script
13 verbose stack Error: apps-script-starter@4.9.0 build: `webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid apps-script-starter@4.9.0
15 verbose cwd D:\jjavi\Documents\git clones\apps-script-starter
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error apps-script-starter@4.9.0 build: `webpack`
22 error Exit status 1
23 error Failed at the apps-script-starter@4.9.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Could you help me please?
Thank you in advance!

**Comment by labnol** [comment]
Can you update the dependencies and try again?

```
ncu -u
npm install
npm run deploy
```
