### ISSUE TITLE
Adding JSDoc support

### ISSUE THREAD

**Issue by mendeljacks** [labnol/apps-script-starter#28]
Google sheets allows JSDoc comments to make descriptions for custom functions:
https://stackoverflow.com/questions/15015373/how-to-add-custom-function-help-to-a-google-spreadsheet-not-the-script-edit

However scripts compiled with the starter don't show up as help text.
The bundling process does not remove the comments as I can see them in the google apps script editor. I suspect it's just not being read because it's nested within the iife?

**Comment by labnol** [comment]
I will soon add an example that will show how to bundle custom Sheet functions with the Apps script starter kit.

**Comment by labnol** [comment]
Please see [this tutorial](https://github.com/labnol/apps-script-starter/blob/master/FUNCTIONS.md) on how to add custom functions with JSDoc comments.
