### ISSUE TITLE
How to load user-defined js file in html?

### ISSUE THREAD

**Issue by sunm0710** [labnol/apps-script-starter#30]
Hello, I really like this tool as a beginner of GAS developer. But I have some issue loading a js script in html file. Is there a recommend way to do this? Thank you!

**Comment by labnol** [comment]
You can use a tool like `gulp` to bundle all the CSS and JS in a single HTML file that can be pushed to the cloud.

I've written a tutorial for [bundling React apps](https://www.labnol.org/code/bundle-react-app-single-file-200514) in a single file but the technique should be similar for vanilla HTML / JS.

````
const gulp = require('gulp')
const inlinesource = require('gulp-inline-source')
const replace = require('gulp-replace')

gulp.task('default', () => {
    return gulp.src('./build/*.html')
        .pipe(replace('.js"></script>', '.js" inline></script>'))
        .pipe(replace('rel="stylesheet">', 'rel="stylesheet" inline>'))
        .pipe(inlinesource({
            compress: false,
            ignore: ['png']
        }))
        .pipe(gulp.dest('./build'))
});
