### ISSUE TITLE
Why ES6 code prettily not available after deployed to AppScript Editor

### ISSUE THREAD

**Issue by lahirue** [labnol/apps-script-starter#31]
Since Google started supporting ES6 in their Appscript, we can directly move our ES6 code to app script. What is the purpose of converting the code into this type ? Is there any advantage ?

function rePayment() {
}(function(e, a) { for(var i in a) e[i] = a[i]; }(this, /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache

**Comment by labnol** [comment]
I would not recommend using the ES6 Chrome runtime for production yet. There are too many issues around triggers, JDBC connections, script authorization, Storage and more.
