### ISSUE TITLE
How/Where can I add a reference to an existing project?

### ISSUE THREAD

**Issue by NoSubstitute** [labnol/apps-script-starter#37]
Hi, I already have a few projects that I'd like to continue develop using your starter kit.
At the end of your video you show how we can _deploy_ to a specific web app.

But can I use _clasp pull_, or something similar, to grab the current existing code _into_ your starter kit structure?
I obviously don't want to create new projects, as some are already used by a lot of people.

**Comment by labnol** [comment]
You can use `npx clasp pull`  to download the existing project into the local folder.

Also, the `.clasp.json` file should have a structure like this:

```
{	
  "scriptId": "<<Script ID>>",	
  "rootDir": "dist"	
}	
```

**Comment by NoSubstitute** [comment]
Yeah, I did that, but ran into so many error messages so I thought there
was something wrong with that process.

Turns out there are instead too many changes in the starter kit since
original publication that your guide doesn't even work anymore.

I think I also need to learn how to disable some of the checks in the
starter kit, as it refuses to build code that I have in production, which I
know works fine.

**Comment by labnol** [comment]
Apps Script moved to V8 runtime and the kit was updated to supported V8.

**Comment by NoSubstitute** [comment]
But, was it necessary to refuse all older code?

Even if I set my code to use V8 runtime, it still works, so it's not really
broken. I mean, I have the code running now, and regardless if I have V8
active or not, it runs fine, without errors, in Sheets, and web apps.

The kit also hides most errors, so I can't even see what's wrong, or how to
fix it.

Anyway, this still means that your guide on how to use the kit is outdated.
