### ISSUE TITLE
Support Webpack 5

### ISSUE THREAD

**Issue by labnol** [labnol/apps-script-starter#41]
Depends on the GAS Webpack plugin. 

https://github.com/fossamagna/gas-webpack-plugin/issues/417

**Comment by fossamagna** [comment]
I published gas-webpack-plugin@2.0.0 for support webpack@5.

https://www.npmjs.com/package/gas-webpack-plugin/v/2.0.0

**Comment by votungphan** [comment]
Not sure if @labnol needs help to support the Webpack@5. I see all required dependencies support the Webpack@5. Thanks and Regards!

**Comment by labnol** [comment]
Thank you @fossamagna https://github.com/labnol/apps-script-starter/commit/a4564e5da4b045d7c2e8015893bd518e910835ae
