### ISSUE TITLE
node-forge@0.9.0 High Severity Vulnerabilities

### ISSUE THREAD

**Issue by Ryzzuh** [labnol/apps-script-starter#42]
https://snyk.io/test/npm/node-forge/0.9.0

**Comment by labnol** [comment]
Wait for Google to update the library version in clasp. See https://github.com/google/clasp/issues/812

**Comment by labnol** [comment]
This is fixed in the latest release of clasp ([v2.4.0](https://github.com/google/clasp/compare/v2.3.1...v2.4.0)). Thank you @Sqrrrl
