### ISSUE TITLE
eslint-config-prettier version 8.x support

### ISSUE THREAD

**Issue by votungphan** [labnol/apps-script-starter#47]
The eslint-config-prettier has released version 8.x which supports the simplicity with "All configs have been merged into one!" and updates relating to  arrow-body-style and prefer-arrow-callback, so any plan to update the **eslint-config-labnol** to be compatible with **eslint-config-prettier version 8.x**?

**Comment by contributorpw** [comment]
It might be worth discarding `eslint-config-labnol`. React tools are superfluous there too.

**Comment by labnol** [comment]
Please see the new release supporting Webpack 5.
