### ISSUE TITLE
Is there a way to debug the code using an IDE?

### ISSUE THREAD

**Issue by vdurante** [labnol/apps-script-starter#49]
I like the idea of developing my script locally, but it seems that there is no way to debug it, since the google functions are not accessible locally.

**Comment by labnol** [comment]
You can write a local mock server that simulates the Google Script API calls and can be invoked only when the `proces.env. NODE_ENV` environment is not `production`.

**Comment by labnol** [comment]
See https://github.com/dan-kushnaryov/gas-mock-globals
