### ISSUE TITLE
bundle.js via gulp for an add-on/script ui

### ISSUE THREAD

**Issue by oshliaer** [labnol/apps-script-starter#5]
Hi!

I have a not complete solution (it's based on this repo) which generate ui environment for the script via gulp. Please share ideas, how do you see the future of the labnol/apps-script-starter SDK? Have you identified a roadmap so that we can make suggestions and PRs?

**Comment by labnol** [comment]
I am also using gulp in one of my Apps Script projects for bundling HTML files before pushing them to the server through clasp. Maybe I will push the code into this repository itself.

**Comment by oshliaer** [comment]
@labnol 

there is my example https://github.com/oshliaer/apps-script-starter/tree/dev
