### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by joshsny** [labnol/apps-script-starter#52]
I'm struggling with using Typescript for GAS together with Babel and Webpack. Was wondering if you have any experience with this related to creating this starter? @labnol

(Feel free to close this issue if not, since it isn't an issue with the project, it's more just for discussion about Typescript support)

**Comment by labnol** [comment]
You may look at this [starter](https://github.com/enuchi/React-Google-Apps-Script) by @enuchi
