### ISSUE TITLE
npm run deploy fails

### ISSUE THREAD

**Issue by russellkt** [labnol/apps-script-starter#7]
npm run deploy fails due to following:

```Push failed. Errors:
Syntax error: Missing : after property ID. line: 11 file: webpack.config
Files to push were:
└─ appsscript.json
└─ dist/code.js
└─ dist/index.html
└─ node_modules/ajv/.tonic_example.js
└─ node_modules/gas-entry-generator/.eslintrc.js
└─ node_modules/gas-webpack-plugin/.eslintrc.js
└─ node_modules/hash.js/.eslintrc.js
└─ node_modules/npm/node_modules/ajv/.tonic_example.js
└─ webpack.config.js

**Comment by russellkt** [comment]
Not sure why but started from scratch and it is working now.  I did have to `npx clasp create` first.  If this is necessary please update docs.  Otherwise thank you so much for creating the project.  It now makes apps script dev and deploy a pleasant experience!!

**Comment by oshliaer** [comment]
@russellkt , please look at [Getting Started] Did you do what is said in point 3?

> 3. Replace the "scriptId" value in the .clasp.json file.

[Getting Started]: https://github.com/labnol/apps-script-starter#getting-started-

**Comment by labnol** [comment]
Please see #20
